apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
  labels:
     name: tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
