apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  ports:
  - name: http
    nodePort: 31870
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: tomcat
  type: NodePort
